name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - uses: astral-sh/setup-uv@v5
        with:
          version: 0.6.3
          enable-cache: true
      - run: uv sync --dev --all-extras
      - run: uv run ruff check
      - run: uv run mypy
